### PR TITLE
Improved deadlock avoidance in updateAcl

### PR DESCRIPTION
**Pull request by beckje01**
We have this in production under load, without this change we get a high number of deadlocks in the DB.

[Review on Reviewable](https://reviewable.io/reviews/grails-plugins/grails-spring-security-acl/16)

### CODE REVIEW

**Comment by confile** [comment]
+1 would be great if this gets merged.

**Comment by confile** [comment]
@beckje01 Do you have an idea on this error: http://stackoverflow.com/questions/31597897/java-lang-string-cannot-be-cast-to-java-lang-long-in-spring-security-acl

**Comment by beckje01** [comment]
Need this one rebased?

**Comment by burtbeckwith** [comment]
No, I'll manually merge into 2.x and 3.x for M2. I didn't include it yet because I wanted to get the M1 release out.

**Comment by beckje01** [comment]
Sure ping me if anything is needed.

**Comment by burtbeckwith** [comment]
Thanks - I manually applied the changes. Will be in 2.0-RC3 and 3.0.0.M2

**Pull request closed without merging**
